services:
    autoheal: 
        restart: always
        image: willfarrell/autoheal
        environment: 
            - AUTOHEAL_CONTAINER_LABEL=all
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
    
    virtuoso-health:
        image: curlimages/curl:latest
        network_mode: host
        command: ["sh", "-c", "while true; do sleep 5; done"]
        healthcheck:
            test: ["CMD", "curl", "-f", "http://localhost:8890"]
            interval: 5s
            timeout: 10s
            retries: 20

    virtuoso:
        image: tenforce/virtuoso:virtuoso7.2.5
        environment:
            - VIRT_SPARQL_MaxQueryCostEstimationTime=default
            - VIRT_SPARQL_MaxQueryExecutionTime=300
            - VIRT_Parameters_ServerThreads=100
            - VIRT_HTTPServer_ServerThreads=100
        volumes: 
            - type: volume
              source: virtuoso-db
              target: /data
        ports:
            - "8890:8890"
        restart: always

    synbiohub:
        image: synbiohub/synbiohub:snapshot-standalone
        depends_on: 
            virtuoso-health:
                condition: service_healthy
        ports:
            - "7777:7777"
        volumes:
            - type: volume
              source: sbh
              target: /mnt
            - type: volume
              source: virtuoso-db
              target: /virtuoso
        restart: always

volumes:
    virtuoso-db:
    sbh:
