  
version: '3.2'

services:
    pluginSubmitExcel:
        image: synbiohub/plugin-submit-excel:snapshot
        ports:
            - "8093:5000"
        volumes:
            - type: volume
              source: pluginSubmitExcel
              target: /mnt
        dns: 8.8.8.8
        restart: always
        depends_on:
            - synbiohub

volumes:
    pluginSubmitExcel:
