version: '3.2'

services:
    explorer:
        image: myersresearchgroup/sbolexplorer:snapshot-synbiohub
        privileged: true  # This replaces the --privileged flag
        ulimits:
            nproc:
                soft: 1024   # Soft limit for number of processes/threads
                hard: 2048   # Hard limit for number of processes/threads
        ports:
            - "13162:13162"
        depends_on:
            - elasticsearch
            - synbiohub
        dns: 8.8.8.8
        volumes:
            - type: volume
              source: explorer
              target: /mnt
    elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:6.3.2
        depends_on: 
            - virtuoso
        ports:
            - "9200:9200"
        volumes:
            - type: volume
              source: esdata
              target: /usr/share/elasticsearch/data

volumes:
    esdata:
    explorer:
