version: '3.2'

services:
    explorer:
        image: michael13162/sbolexplorer:latest
        ports:
            - "13162:13162"
        depends_on:
            - elasticsearch
    elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:6.3.2
        ports:
            - "6200:6200"
    virtuoso:
        image: tenforce/virtuoso:1.3.1-virtuoso7.2.4
        volumes: 
            - type: volumne
              source: virtuoso-db
              target: /data
        ports:
            - "8890:8890"
    synbiohub:
        image: synbiohub/synbiohub:snapshot-standalone
        depends_on: 
            - virtuoso
        ports:
            - "7777:7777"
        volumes:
            - type: volume
              source: sbh
              target: /mnt
        dns: 8.8.8.8

volumes:
    virutoso-db:
    sbh:
