version: '3.2'

services:
    pluginSubmitSnapgene:
        image: synbiohub/snapgene-submit-plugin:snapshot
        ports:
            - "8084:5000"
        volumes:
            - type: volume
              source: pluginSubmitSnapgene
              target: /mnt
        dns: 8.8.8.8
        restart: always
        depends_on:
            - synbiohub

volumes:
    pluginSubmitSnapgene:
