version: '3.2'

services:
    pluginSubmitTestJs:
        image: synbiohub/plugin-submit-test-js:snapshot
        ports:
            - "8091:5000"
        volumes:
            - type: volume
              source: pluginSubmitTestJs
              target: /mnt
        dns: 8.8.8.8
        restart: always
        depends_on:
            - synbiohub

volumes:
    pluginSubmitTestJs:
