version: '3.2'

services:
    explorer:
        image: michael13162/sbolexplorer:snapshot-synbiohub
        ports:
            - "13162:13162"
            - "127.0.0.1:13162:13162"
        depends_on:
            - elasticsearch
            - synbiohub
        dns: 8.8.8.8
    elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:6.3.2
        ports:
            - "6200:6200"
        volumes:
            - esdata:/usr/share/elasticsearch/data
    virtuoso:
        image: tenforce/virtuoso:virtuoso7.2.5
        volumes: 
            - type: volumne
              source: virtuoso-db
              target: /data
        ports:
            - "8890:8890"
            - "127.0.0.1:8890:8890"
    synbiohub:
        image: synbiohub/synbiohub:snapshot-standalone
        depends_on: 
            - virtuoso
        ports:
            - "7777:7777"
        volumes:
            - type: volume
              source: sbh
              target: /mnt
        dns: 8.8.8.8

volumes:
    virtuoso-db:
    sbh:
    esdata:
