version: '3.2'

services:
    explorer:
        image: michael13162/sbolexplorer:snapshot-synbiohub
        ports:
            - "13162:13162"
        depends_on:
            - elasticsearch
            - synbiohub
        dns: 8.8.8.8
        volumes:
            - type: volume
              source: explorer
              target: /mnt
    elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:6.3.2
        ports:
            - "6200:6200"
        volumes:
            - esdata:/usr/share/elasticsearch/data

volumes:
    esdata:
    explorer:
